/**
 * Common
 */
export const GET_TUTORIAL_TIPS = 'GET_TUTORIAL_TIPS'
export const GET_USER = 'GET_USER'

/**
 * Behavior
 */
export const POST_BEHAVIOR = 'POST_BEHAVIOR'

/**
 * Process
 */
export const GET_PROCESSES = 'GET_PROCESSES'
export const GET_PROCESSES_PID = 'GET_PROCESSES_PID'

/**
 * New Dashboard
 */
export const POST_DASHBOARD_LABELS = 'POST_DASHBOARD_LABELS'
export const GET_DASHBOARD_CONFIG = 'GET_DASHBOARD_CONFIG'
export const POST_DASHBOARD_QUERY = 'POST_DASHBOARD_QUERY'
export const POST_DASHBOARD_QUERY_RANGE = 'POST_DASHBOARD_QUERY_RANGE'

/**
 * OamServer
 */
export const GET_APP_RESOURCES_TOPOLOGY = 'GET_APP_RESOURCES_TOPOLOGY'
export const GET_APP_RESOURCES_DETAIL = 'GET_APP_RESOURCES_DETAIL'
export const GET_APPLICATION = 'GET_APPLICATION'
export const PUT_APPLICATION = 'PUT_APPLICATION'
export const DELETE_APPLICATION = 'DELETE_APPLICATION'
export const POST_BDC_APPLICATION = 'POST_BDC_APPLICATION'
export const GET_BDC_APPLICATION_DEFINITION_SCHEMA = 'GET_BDC_APPLICATION_DEFINITION_SCHEMA'
export const GET_BDCS = 'GET_BDCS'
export const GET_BDC = 'GET_BDC'
export const GET_BDC_CONTEXT_SECRET_DEFINITION_SCHEMA = 'GET_BDC_CONTEXT_SECRET_DEFINITION_SCHEMA'
export const GET_BDC_CONTEXT_SECRETS = 'GET_BDC_CONTEXT_SECRETS'
export const GET_BDC_CONTEXT_SECRET = 'GET_BDC_CONTEXT_SECRET'
export const GET_BDC_CONTEXT_SETTING_DEFINITION_SCHEMA = 'GET_BDC_CONTEXT_SETTING_DEFINITION_SCHEMA'
export const GET_BDC_CONTEXT_SETTINGS = 'GET_BDC_CONTEXT_SETTINGS'
export const GET_BDC_CONTEXT_SETTING = 'GET_BDC_CONTEXT_SETTING'
export const GET_APP_KIND_RESOURCES_DETAIL = 'GET_APP_KIND_RESOURCES_DETAIL'
export const GET_APP_DETAIL = 'GET_APP_DETAIL'
export const GET_APPLICATION_PODS = 'GET_APPLICATION_PODS'
export const GET_APPLICATION_POD_DETAIL = 'GET_APPLICATION_POD_DETAIL'
export const GET_APPLICATION_SERVICE_ENDPOINTS = 'GET_APPLICATION_SERVICE_ENDPOINTS'
export const DELETE_APPLICATION_POD = 'DELETE_APPLICATION_POD'
export const GET_APPLICATIONS = 'GET_APPLICATIONS'
export const GET_APPLICATION_POD_CONTAINER_LOGS = 'GET_APPLICATION_POD_CONTAINER_LOGS'

/**
 * catalog manager service
 */
export const GET_CATALOGS = 'GET_CATALOGS'
export const GET_CATALOG = 'GET_CATALOG'
export const GET_CATALOGS_README = 'GET_CATALOGS_README'
export const GET_CATALOGS_APP_FORMS = 'GET_CATALOGS_APP_FORMS'
export const GET_CATALOGS_APP_FORM = 'GET_CATALOGS_APP_FORM'
export const GET_CATALOGS_APP_FORMS_DATA = 'GET_CATALOGS_APP_FORMS_DATA'
export const GET_CATALOGS_APP_FORMS_INSTALL = 'GET_CATALOGS_APP_FORMS_INSTALL'
export const GET_CATALOGS_APP_FORMS_README = 'GET_CATALOGS_APP_FORMS_README'
export const GET_CATALOGS_APP_FORMS_APPS = 'GET_CATALOGS_APP_FORMS_APPS'
