name: Build KDP UX

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

env:
  VERSION: "v1.0.0-240407"
  APP_NAME: "linktimecloud/kdp-ux"
  DOCKER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.REG_USER }}
  DOCKER_PASSWORD: ${{ secrets.REG_PASSWD }}

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Build successful
        run: echo "Docker image name is ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.VERSION }}"
