name: Run Unit Tests of Web App

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "release*"

jobs:
  lint-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and lint
        working-directory: web
        run: |
          yarn install
          yarn lint

  lint-test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and test
        working-directory: frontend
        env:
          NODE_ENV: test
        run: |
          yarn install
          yarn lint
          yarn run unit:coverage
          echo "Test finished!"
